export enum FacilityType {
  DEFAULT = 1, // Wat
  AMP_STATION = 2,
  BIO_LAB = 3,
  TECH_PLANT = 4,
  LARGE_OUTPOST = 5,
  SMALL_OUTPOST = 6,
  WARPGATE = 7,
  INTERLINK_FACILITY = 8,
  CONSTRUCTION_OUTPOST = 9,
  RELIC_OUTPOST = 10, // Desolation only
  CONTAINMENT_SITE = 11,
  TRIDENT = 12
}
