export enum Vehicle {
  FLASH = 1,
  SUNDERER = 2,
  LIGHTNING = 3,
  MAGRIDER = 4,
  VANGUARD = 5,
  PROWLER = 6,
  SCYTHE = 7,
  REAVER = 8,
  MOSQUITO = 9,
  LIBERATOR = 10,
  GALAXY = 11,
  HARASSER = 12,
  DROP_POD = 13,
  VALKYRIE = 14,
  ANT = 15,
  XIPHOS_AP_PHALANX_TURRET = 100,
  MANA_AP_TURRET = 101,
  MANA_AV_TURRET = 102,
  SPITFIRE_TURRET = 103, // Don't think is used
  SPITFIRE_AUTO_TURRET = 104, // Think this is used
  SPITFIRE_AA_TURRET = 105, // Not used
  ASPIS_AA_PHALANX_TURRET = 150, // Base AA Turret
  SPEAR_AV_PHALANX_TURRET = 151, // Base AV Turret
  SPEAR_AV_PHALANX_TOWER = 160, // Player Base AV Turret
  ASPIS_AA_PHALANX_TOWER = 161, // Player Base AA Turret
  XIPHOS_AP_TOWER = 162, // Player Base AI Turret
  GLAIVE_IPC = 163, // Player Base Artillery
  RECON_DRONE = 1013, // Never implemented
  OBSERVER_CAMERA = 1337,
  AUTO_TURRET = 2003, // Never implemented
  SPEAR_AV_PHALANX_TURRET_2 = 2006, // Player Base towerless AV turret
  COLOSSUS = 2007,
  DROP_POD_2 = 2008, // Drop Pod Mrk 2? o.O
  XIPHOS_AP_TURRET = 2009, // Wat?
  FLASH_XS_1 = 2010, // Outfit Merit Flash
  FORWARD_STATION = 2011, // Not used also... o.O
  BASTION = 2019, // API says it's a Light Aircraft... LUL
  FLAIL = 2021, // Flail player base
  JAVELIN = 2013,
  JAVELIN_2 = 2033, // Again?
  PUMPKIN_PATCH = 2036, // Pumpkins are vehicles apparently
  DELIVERER_PROTOTYPE = 2039, // Spawn ANT
  WASP_PROTOTYPE = 2040, // Cortium Valkrie
  MOSQUITO_INTERCEPTOR = 2122, // Bastion Mosquito
  REAVER_INTERCEPTOR = 2123, // Bastion Reaver
  SCYTHE_INTERCEPTOR = 2124, // Bastion Scythe
  JAVELIN_3 = 2125, // Again... again?
  SPITFIRE_AUTO_TURRET_2 = 2128, // Duplicate or reworked version?
  DERVISH = 2136,
  CHIMERA = 2137,
  DELIVERER_PROTOTYPE_2 = 2139, // Currently used (Spawn ANT)
  LODESTAR_PROTOTYPE_2 = 2140, // Currently used (Spawn Galaxy)
  WASP_PROTOTYPE_2 = 2141, // Currently used (Cortium Valkrie)
  EXODUS_PPC = 2143, // Big Pew Pew on the Oshur carriers
}
