// Allowed vehicles to show up in the matrix (both alert and on the stats page)
import { Vehicle } from '@/ps2alerts-constants/vehicle'

export const allowedVehicleMatrixArray = [
  Vehicle.FLASH,
  Vehicle.SUNDERER,
  Vehicle.LIGHTNING,
  Vehicle.MAGRIDER,
  Vehicle.VANGUARD,
  Vehicle.PROWLER,
  Vehicle.SCYTHE,
  Vehicle.REAVER,
  Vehicle.MOSQUITO,
  Vehicle.LIBERATOR,
  Vehicle.GALAXY,
  Vehicle.VALKYRIE,
  Vehicle.ANT,
  Vehicle.JAVELIN_2,
  Vehicle.COLOSSUS,
  Vehicle.DERVISH,
  Vehicle.CHIMERA,
  Vehicle.CORSAIR,
]

// Allowed vehicles to show up in the vehicles totals in the statistics page (all vehicles per alert are allowed as they're filtered by the context of that alert anyway)
export const allowedStatisticsVehiclesArray = [
  Vehicle.FLASH,
  Vehicle.SUNDERER,
  Vehicle.LIGHTNING,
  Vehicle.MAGRIDER,
  Vehicle.VANGUARD,
  Vehicle.PROWLER,
  Vehicle.SCYTHE,
  Vehicle.REAVER,
  Vehicle.MOSQUITO,
  Vehicle.LIBERATOR,
  Vehicle.GALAXY,
  Vehicle.VALKYRIE,
  Vehicle.ANT,
  Vehicle.COLOSSUS,
  Vehicle.JAVELIN_2,
  Vehicle.DROP_POD,
  Vehicle.XIPHOS_AP_PHALANX_TURRET,
  Vehicle.MANA_AP_TURRET,
  Vehicle.MANA_AV_TURRET,
  Vehicle.SPITFIRE_TURRET,
  Vehicle.ASPIS_AA_PHALANX_TURRET,
  Vehicle.SPEAR_AV_PHALANX_TURRET,
  Vehicle.SPEAR_AV_PHALANX_TOWER,
  Vehicle.ASPIS_AA_PHALANX_TOWER,
  Vehicle.XIPHOS_AP_TOWER,
  Vehicle.GLAIVE_IPC,
  Vehicle.PHOENIX_MISSILE,
  Vehicle.SPEAR_AV_PHALANX_TURRET_2,
  Vehicle.FLASH_XS_1,
  Vehicle.BASTION,
  Vehicle.FLAIL,
  Vehicle.DELIVERER_PROTOTYPE,
  Vehicle.WASP_PROTOTYPE,
  Vehicle.LODESTAR_PROTOTYPE_2,
  Vehicle.MOSQUITO_INTERCEPTOR,
  Vehicle.SCYTHE_INTERCEPTOR,
  Vehicle.DERVISH,
  Vehicle.CHIMERA,
  Vehicle.CORSAIR,
]
