---
- hosts: localhost
  vars:
    root_dir: "{{ playbook_dir }}/../../"
  tasks:
    - debug:
        msg: "========= 🕸️  Starting Website module 🕸️  ========="

    - name: Delete dist folder
      file:
        path: "{{ root_dir }}/dist"
        state: absent

    - name: Delete nuxt folder
      file:
        path: "{{ root_dir }}/.nuxt"
        state: absent

    - name: Start Website Dev container
      docker_container:
        name: ps2alerts-website
        image: ps2alerts/website:dev
        state: started
        restart: no
        recreate: yes
        interactive: yes
        tty: yes
        volumes:
          - "{{ root_dir | realpath }}:/app:rw"
        ports:
          - "3001"
        networks:
          - name: "ps2alerts"
        env:
          APP_PORT: "3001" # Not 3000 as that conflicts with API, locally
          BUILT: "Now ;)"
          ENV: "development"
          VERSION: "DEV"
          BUILD: "DEV BUILD"
          API_HOST: "https://dev.api.ps2alerts.com"
          GOOGLE_PROPERTY: "G-620HJF2H4L"
          BASE_URL: "https://dev.ps2alerts.com"
        labels:
          traefik.enable: "true"
          traefik.http.routers.ps2alerts_website_http.rule: "Host(`dev.ps2alerts.com`)"
          traefik.http.routers.ps2alerts_website_http.entrypoints: "web"
          traefik.http.routers.ps2alerts_website.middlewares: "redirect-to-https"
          traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: "https"
          traefik.http.routers.ps2alerts_website.entrypoints: "websecure"
          traefik.http.routers.ps2alerts_website.rule: "Host(`dev.ps2alerts.com`)"
          traefik.http.routers.ps2alerts_website.tls: "true"
          traefik.http.routers.ps2alerts_website.tls.domains[0].main: "dev.ps2alerts.com"
