---
- hosts: localhost
  vars:
    root_dir: "{{ playbook_dir }}/../../"
  tasks:
    - debug:
        msg: "========= 🕸️  Starting Website module 🕸️  ========="

    - name: Delete dist folder
      file:
        path: "{{ root_dir }}/dist"
        state: absent

    - name: Delete nuxt folder
      file:
        path: "{{ root_dir }}/.nuxt"
        state: absent

    - name: Start Website Dev container
      docker_container:
        name: ps2alerts-website
        image: ps2alerts/website:dev
        state: started
        restart: no
        recreate: yes
        interactive: yes
        tty: yes
        volumes:
          - "{{ root_dir | realpath }}:/app:rw"
        ports:
          - "80"
        networks:
          - name: "ps2alerts"
        env:
          BUILT: "Now ;)"
          ENV: "development"
          VERSION: "v3.0.0-dev"
          BUILD: "abc12345"
          API_HOST: "http://dev.api.ps2alerts.com"
          GOOGLE_PROPERTY: "G-620HJF2H4L"
          BASE_URL: "http://dev.ps2alerts.com"
        labels:
          traefik.enable: "true"
          traefik.http.routers.ps2alerts_website.rule: "Host(`dev.ps2alerts.com`)"
          traefik.http.routers.ps2alerts_website.service: "ps2alerts_website_service"
          traefik.http.services.ps2alerts_website_service.loadbalancer.server.port: "3000"
          traefik.http.services.ps2alerts_website_service.loadbalancer.server.scheme: "http"
          traefik.http.services.ps2alerts_website_service.loadbalancer.passhostheader: "true"
