apiVersion: v1
kind: Service
metadata:
  name: {{ application }}-{{ environment }}
  namespace: ps2alerts
spec:
  selector:
    app: {{ application }}-{{ environment }}
  ports:
    - protocol: TCP
      port: {{ port }}
      targetPort: {{ port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ application }}-{{ environment }}
  namespace: ps2alerts
  labels:
    app: {{ application }}-{{ environment }}
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ application }}-{{ environment }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ application }}-{{ environment }}
        version: {{ version }}
    spec:
      containers:
        - name: application
          image: maelstromeous/applications:{{ application }}-{{ environment }}-{{ version }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "150m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: {{ port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ port }}
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 5
          env:
            - name: ENVIRONMENT
              value: "{{ environment }}"
            - name: VERSION
              value: "{{ version }}"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ application }}-{{ environment }}
  namespace: ps2alerts
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ application }}-{{ environment }}
  minReplicas: {{ min_replicas }}
  maxReplicas: {{ max_replicas }}
  targetCPUUtilizationPercentage: 75
