---
name: Typescript Compile
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read

jobs:
  typescript-compile:
    name: Typescript Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Install node v22
        uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Install modules
        run: yarn install

      - name: Build application
        run: yarn run build
