---
name: Typescript Compile
on:
  push:
    branches: [dev]
  pull_request:
jobs:
  typescript-compile:
    name: Typescript Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Install node v16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install modules
        run: yarn install

      - name: Build application
        run: yarn run build
