---
name: Typescript Compile
on:
  push:
    branches: [revive]
  pull_request:
jobs:
  typescript-compile:
    name: Typescript Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node v16
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16
      - name: Install modules
        run: yarn install
      - name: Build application
        run: yarn run build
