---
name: Typescript Compile
on:
  push:
    branches: [revive]
  pull_request:
jobs:
  typescript-compile:
    name: Typescript Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v16
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
      - name: Install
        run: yarn install
      - name: Build
        run: yarn run build
